
# CONFIG FILE OR JSON...
"""
specs = [
    {"descr": "debit_sans_pluie",
     "customer": "cust_1002343",
     "eq_id":"eq_333333",
     "model_type":"influx_operation",
     "upstream": ["eq_111111", "eq_222222"],
     "params": {"formula":"je prends le débit mais ... sans la pluie"},
     "computation_frequency":300
     },
     {"descr": "pluie",
      "customer": "cust_1002343",
     "eq_id":"eq_111111",
     "model_type":"source",
     "upstream": [],
     "params": {},
     "computation_frequency":60
     },
     {"descr": "debit_entrant",
      "customer": "cust_1002343",
     "eq_id":"eq_222222",
     "model_type":"source",
     "upstream": [],
     "params": {},
     "computation_frequency":600},
    {"descr": "prediction_debit_sans_pluie",
     "eq_id":"eq_444444",
     "customer": "cust_1002343",
     "model_type":"time_series",
     "upstream": ["eq_333333"],
     "params":{"day":1,
                "week":1,
                "year":0},
    "computation_frequency":[3600, 86400]},
    {"descr": "debit_sans_pluie",
     "customer": "cust_1001212",
     "eq_id":"eq_888888",
     "model_type":"influx_operation",
     "upstream": ["eq_555555", "eq_555666"],
     "params": {"formula":"inflow_without_rain"},
     "computation_frequency":300
     },
     {"descr": "debit_entrant",
      "customer": "cust_1001212",
     "eq_id":"eq_555555",
     "model_type":"source",
     "upstream": [],
     "params": {},
     "computation_frequency":600},
    {"descr": "prediction_debit_sans_pluie",
     "customer": "cust_1001212",
     "eq_id":"eq_777777",
     "model_type":"time_series",
     "upstream": ["eq_888888"],
     "params":{"day":1,
                "week":1,
                "year":0},
    "computation_frequency":[3600, 86400]},

]"""



specs = [
    {"descr": "pluie",
    "customer": "cust_1002343",
     "eq_id":"eq_111111",
     "model_type":"source",
     "computation_frequency":60
     },
     {"descr": "debit_entrant",
      "customer": "cust_1002343",
     "eq_id":"eq_222222",
     "model_type":"source",
     "computation_frequency":300},
    {"descr": "debit_sans_pluie",
     "customer": "cust_1002343",
     "eq_id":"eq_333333",
     "model_type":"influx_operation",
     "upstreams": ["eq_111111", "eq_222222"],
     "interpolation_type":"linear",
    "time_preprocessing":"Now",
    "params":{"influx_type":"A without B"},
     "computation_frequency":120,
     "refresh_on_upstreams_up":["eq_222222"]},
     {"descr": "prediction_debit_sans_pluie",
     "eq_id":"eq_444444",
     "customer": "cust_1002343",
     "model_type":"time_series",
     "upstreams": ["eq_333333"],
     "interpolation_type":"linear",
     "time_preprocessing":"Now",
     "params":{"horizon":86400},
    "computation_frequency":None,
    "refresh_on_upstreams_up":['eq_333333']},
    {"descr": "prediction_debit_sans_pluie_training",
     "eq_id":"eq_444444_training",
     "customer": "cust_1002343",
     "model_type":"time_series_training",
     "upstreams": ["eq_333333"],
     "interpolation_type":"linear",
     "time_preprocessing":"Now",
     "params":{"day":1,
                "week":1,
                "year":0},
    "computation_frequency":600},
    {"descr": "pluie",
    "customer": "cust_1007685",
     "eq_id":"eq_12121212",
     "model_type":"source",
     "computation_frequency":60
     },
     {"descr": "debit_entrant",
      "customer": "cust_1007685",
     "eq_id":"eq_23232323",
     "model_type":"source",
     "computation_frequency":300},
    {"descr": "debit_sans_pluie",
     "customer": "cust_1007685",
     "eq_id":"eq_34343434",
     "model_type":"influx_operation",
     "upstreams": ["eq_23232323", "eq_12121212"],
     "interpolation_type":"linear",
    "time_preprocessing":"Now",
    "params":{"influx_type":"A without B"},
     "computation_frequency":120,
     "refresh_on_upstreams_up":["eq_23232323"]},
     {"descr": "prediction_debit_sans_pluie",
     "eq_id":"eq_45454545",
     "customer": "cust_1007685",
     "model_type":"time_series",
     "upstreams": ["eq_34343434"],
     "interpolation_type":"linear",
     "time_preprocessing":"Now",
     "params":{"horizon":86400},
    "computation_frequency":None,
    "refresh_on_upstreams_up":['eq_34343434']},
    {"descr": "prediction_debit_sans_pluie_training",
     "eq_id":"eq_45454545_training",
     "customer": "cust_1007685",
     "model_type":"time_series_training",
     "upstreams": ['eq_34343434'],
     "interpolation_type":"linear",
     "time_preprocessing":"Now",
     "params":{"day":1,
                "week":1,
                "year":0},
    "computation_frequency":600}]

